name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: app
          MYSQL_PASSWORD: password
    runs:
      using: 'docker'
      image: 'Dockerfile'
      env:
        MYSQL_USER: app
        MYSQL_PASSWORD: password

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec db:create db:migrate db:seed RAILS_ENV=test
        bundle exec rake
